package com.snake.client.domain;

public enum GameEvents {
    INCREASE_SCORE, SNAKE_DEAD, GAME_OVER, RESTART,
    SNAKE_MOVE_LEFT, SNAKE_MOVE_RIGHT, SNAKE_MOVE_UP,
    SNAKE_MOVE_DOWN, SNAKE_BOOST, SNAKE_STOP_BOOST;
}
